### PR TITLE
Release/1.2.1

### PR DESCRIPTION
**Pull request by isuttell**

### CODE REVIEW

**Comment by ThinkTankShark** [comment]
@isuttell the code looks good but there are changes like the release a couple of weeks ago that might lead to instability. Have you tested this in a couple of env and apps to make sure it's doing what you are expected to do?

**Comment by JaredBoone** [comment]
Testing this in my app now.

**Comment by JaredBoone** [comment]
This seems to be working well for me. The pidfile is now being created.

**Comment by JaredBoone** [comment]
I'll publish

**Comment by isuttell** [comment]
> @isuttell the code looks good but there are changes like the release a couple of weeks ago that might lead to instability. Have you tested this in a couple of env and apps to make sure it's doing what you are expected to do?

I tested locally in both Watch and Dock. We definitely need to test more before we deploy to production though.

**Pull request merged**
